version: '2'
services:

  postgres:
    image: sameersbn/postgresql:9.5-3
    env_file: ./docker/.env-postgres

  directory_api_webserver:
    image: ukti/directory-api:latest
    depends_on: [postgres]
    links: [postgres]
    working_dir: /usr/src/app
    entrypoint: dockerize -wait tcp://postgres:5432 -timeout 120s
    command: ./docker/cmd-integration-test-webserver.sh
    ports: ["8000:8000"]
    env_file: ./docker/directory-api/.env

  directory_api_queue_worker:
    image: ukti/directory-api:latest
    depends_on: [postgres]
    links: [postgres]
    working_dir: /usr/src/app
    entrypoint: dockerize -wait tcp://postgres:5432 -timeout 120s
    command: ./docker/cmd-queue_worker.sh
    env_file: ./docker/directory-api/.env

  directory_ui_buyer_webserver:
    image: ukti/directory-ui-buyer:latest
    depends_on: [directory_api_webserver]
    links: [directory_api_webserver]
    container_name: find-a-buyer.export.great.docker
    working_dir: /usr/src/app
    command: ./docker/cmd-webserver.sh
    ports: ["8001:8001"]
    env_file: ./docker/directory-ui-buyer/.env

  directory_ui_supplier_webserver:
    image: ukti/directory-ui-supplier:latest
    depends_on: [directory_api_webserver]
    links: [directory_api_webserver]
    container_name: trade.great.docker
    working_dir: /usr/src/app
    command: ./docker/cmd-webserver.sh
    ports: ["8002:8002"]
    env_file: ./docker/directory-ui-supplier/.env

  directory_sso_webserver:
    image: ukti/directory-sso:latest
    depends_on: [postgres]
    links: [postgres]
    working_dir: /usr/src/app
    entrypoint: dockerize -wait tcp://postgres:5432 -timeout 120s
    command: ./docker/cmd-integration-test-webserver.sh
    ports: ["8003:8003"]
    env_file: ./docker/directory-sso/.env

  directory_sso_proxy:
    image: ukti/directory-sso-proxy:latest
    depends_on: [directory_sso_webserver]
    links: [directory_sso_webserver]
    container_name: sso.trade.great.docker
    working_dir: /usr/src/app
    entrypoint: dockerize -wait http://directory_sso_webserver:8003/api/v1/ -timeout 120s
    command: ./docker/cmd-webserver.sh
    ports: ["8004:8004"]
    env_file: ./docker/directory-sso-proxy/.env

  directory_tests_local:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    command: ./docker/cmd-run.sh
    env_file: ./docker/.env
    restart: "no"
