version: '2'
services:

  exred_tests_first_browser_set:
    build:
      context: .
      dockerfile: Dockerfile-exred
    working_dir: /usr/src/app
    command: ./docker/cmd-exred-first-browser-set.sh
    env_file: ./docker/.env
    volumes:
      - ./tests/exred/reports:/usr/src/app/tests/exred/reports
      - ./tests/exred/screenshots:/usr/src/app/tests/exred/screenshots

  exred_tests_second_browser_set:
    build:
      context: .
      dockerfile: Dockerfile-exred
    working_dir: /usr/src/app
    command: ./docker/cmd-exred-second-browser-set.sh
    env_file: ./docker/.env
    volumes:
      - ./tests/exred/reports:/usr/src/app/tests/exred/reports
      - ./tests/exred/screenshots:/usr/src/app/tests/exred/screenshots
