version: '2.1'
services:

  smoke_tests:
    build:
      context: .
      dockerfile: Dockerfile-smoke
    working_dir: /usr/src/app
    command: ./docker/cmd-smoke.sh
    env_file: ./docker/.env
    restart: "no"

  functional_tests:
    build:
      context: .
      dockerfile: Dockerfile-functional
    working_dir: /usr/src/app
    command: ./docker/cmd-functional.sh
    env_file: ./docker/.env
    restart: "no"

  hub:
    image: selenium/hub:3.6.0-bromine
    ports:
      - 4444:4444
    volumes:
      - /dev/shm:/dev/shm
    privileged: true

  chrome:
    image: selenium/node-chrome:3.6.0-bromine
    depends_on:
      - hub
    volumes:
      - /dev/shm:/dev/shm
    privileged: true
    environment:
      - SELENIUM_HUB_HOST=hub
      - SELENIUM_HUB_PORT=4444

  firefox:
    image: selenium/node-firefox:3.6.0-bromine
    depends_on:
      - hub
    volumes:
      - /dev/shm:/dev/shm
    privileged: true
    environment:
      - PICK_ALL_RANDOM_PORTS=true
      - SELENIUM_HUB_HOST=hub
      - SELENIUM_HUB_PORT=4444

#  chrome:
#    links: [hub]
#    volumes:
#      - /dev/shm:/dev/shm
#    environment:
#      - HUB_PORT_4444_TCP_ADDR="hub"
#      - HUB_PORT_4444_TCP_PORT="4444"
#
#  firefox:
#    links: [hub]
#    shm_size: 2g
#    environment:
#      - HUB_PORT_4444_TCP_ADDR="hub"
#      - HUB_PORT_4444_TCP_PORT="4444"

  phantomjs:
    image: selenium/node-phantomjs:3.6.0-bromine
    depends_on:
      - hub
    privileged: true
    environment:
      - PHANTOMJS_OPTS="--ignore-ssl-errors=true"
      - SELENIUM_HUB_HOST=hub
      - SELENIUM_HUB_PORT=4444


  exred_tests:
    depends_on: [hub, chrome, firefox, phantomjs]
    links: [hub, chrome, firefox, phantomjs]
    build:
      context: .
      dockerfile: Dockerfile-exred
    working_dir: /usr/src/app
    entrypoint: dockerize -wait http://hub:4444/grid/console -timeout 20s
    command: ./docker/cmd-exred.sh
    env_file: ./docker/.env
    restart: "no"
