version: '2'
services:

  directory_tests_local:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    command: ./docker/cmd-run.sh
    env_file: ./docker/.env
    restart: "no"
