version: '2'
services:

  postgres:
    image: postgres:9.5.2
    env_file: ./docker/directory-api/.env-postgres

  directory_api_webserver:
    image: ukti/directory-api:latest
    depends_on: [postgres]
    links: [postgres]
    working_dir: /usr/src/app
    entrypoint: dockerize -wait tcp://postgres:5432 -timeout 20s
    command: ./docker/cmd-webserver.sh
    ports: ["8000:8000"]
    env_file: ./docker/directory-api/.env

  directory_api_queue_worker:
    image: ukti/directory-api:latest
    depends_on: [postgres]
    links: [postgres]
    working_dir: /usr/src/app
    entrypoint: dockerize -wait tcp://postgres:5432 -timeout 20s
    command: ./docker/cmd-queue_worker.sh
    env_file: ./docker/directory-api/.env

  directory_ui_webserver:
    image: ukti/directory-ui:latest
    depends_on: [directory_api_queue_worker]
    links: [directory_api_webserver]
    working_dir: /usr/src/app
    command: ./docker/cmd-webserver.sh
    ports: ["8001:8001"]
    env_file: ./docker/directory-ui/.env

  directory_tests_local:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on: [directory_ui_webserver, directory_api_webserver]
    links: [directory_ui_webserver, directory_api_webserver]
    working_dir: /usr/src/app
    entrypoint: dockerize -wait http://directory_ui_webserver:8001 -timeout 30s -wait http://directory_api_webserver:8000 -timeout 30s
    command: ./docker/cmd-run.sh
    env_file: ./docker/.env
    restart: "no"

  directory_tests_shell:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on: [directory_ui_webserver, directory_api_webserver]
    links: [directory_ui_webserver, directory_api_webserver]
    working_dir: /usr/src/app
    command: sh
    env_file: ./docker/.env
    restart: "no"
